// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public let foo: String
    public let foo0: String

    private enum CodingKeys: String, CodingKey {
        case foo = "Foo"
        case foo0 = "foo"
    }
}
