use jtd_codegen::target::{self, inflect, metadata};
use jtd_codegen::Result;
use lazy_static::lazy_static;
use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::io::Write;

lazy_static! {
    static ref KEYWORDS: BTreeSet<String> = include_str!("keywords")
        .lines()
        .map(str::to_owned)
        .collect();
    static ref TYPE_NAMING_CONVENTION: Box<dyn inflect::Inflector + Send + Sync> =
        Box::new(inflect::KeywordAvoidingInflector::new(
            KEYWORDS.clone(),
            inflect::CombiningInflector::new(inflect::Case::pascal_case())
        ));
    static ref FIELD_NAMING_CONVENTION: Box<dyn inflect::Inflector + Send + Sync> =
        Box::new(inflect::KeywordAvoidingInflector::new(
            KEYWORDS.clone(),
            inflect::TailInflector::new(inflect::Case::camel_case())
        ));
    static ref ENUM_MEMBER_NAMING_CONVENTION: Box<dyn inflect::Inflector + Send + Sync> =
        Box::new(inflect::KeywordAvoidingInflector::new(
            KEYWORDS.clone(),
            inflect::TailInflector::new(inflect::Case::camel_case())
        ));
}

pub struct Target {}

impl Target {
    pub fn new() -> Self {
        Self {}
    }
}

impl jtd_codegen::target::Target for Target {
    type FileState = FileState;

    fn strategy(&self) -> target::Strategy {
        target::Strategy {
            file_partitioning: target::FilePartitioningStrategy::SingleFile("GeneratedTypes.swift".into()),
            enum_member_naming: target::EnumMemberNamingStrategy::Unmodularized,
            optional_property_handling: target::OptionalPropertyHandlingStrategy::NativeSupport,
            booleans_are_nullable: false,
            int8s_are_nullable: false,
            uint8s_are_nullable: false,
            int16s_are_nullable: false,
            uint16s_are_nullable: false,
            int32s_are_nullable: false,
            uint32s_are_nullable: false,
            float32s_are_nullable: false,
            float64s_are_nullable: false,
            strings_are_nullable: false,
            timestamps_are_nullable: false,
            arrays_are_nullable: false,
            dicts_are_nullable: false,
            aliases_are_nullable: false,
            enums_are_nullable: false,
            structs_are_nullable: false,
            discriminators_are_nullable: false,
        }
    }

    fn name(&self, kind: target::NameableKind, parts: &[String]) -> String {
        match kind {
            target::NameableKind::Type => TYPE_NAMING_CONVENTION.inflect(parts),
            target::NameableKind::Field => FIELD_NAMING_CONVENTION.inflect(parts),
            target::NameableKind::EnumMember => ENUM_MEMBER_NAMING_CONVENTION.inflect(parts),
        }
    }

    fn expr(&self, state: &mut FileState, metadata: metadata::Metadata, expr: target::Expr) -> String {
        if let Some(s) = metadata.get("swiftType").and_then(|v| v.as_str()) {
            return s.into();
        }

        match expr {
            target::Expr::Empty => {
                state.needs_any_codable = true;
                "AnyCodable".into()
            }
            target::Expr::Boolean => "Bool".into(),
            target::Expr::Int8 => "Int8".into(),
            target::Expr::Uint8 => "UInt8".into(),
            target::Expr::Int16 => "Int16".into(),
            target::Expr::Uint16 => "UInt16".into(),
            target::Expr::Int32 => "Int32".into(),
            target::Expr::Uint32 => "UInt32".into(),
            target::Expr::Float32 => "Float".into(),
            target::Expr::Float64 => "Double".into(),
            target::Expr::String => "String".into(),
            target::Expr::Timestamp => "Date".into(),
            target::Expr::ArrayOf(sub_expr) => format!("[{}]", sub_expr),
            target::Expr::DictOf(sub_expr) => format!("[String: {}]", sub_expr),
            target::Expr::NullableOf(sub_expr) => format!("{}?", sub_expr),
        }
    }

    fn item(
        &self,
        out: &mut dyn Write,
        state: &mut FileState,
        item: target::Item,
    ) -> Result<Option<String>> {
        Ok(match item {
            target::Item::Auxiliary { .. } => {
                None
            }

            target::Item::Preamble => {
                writeln!(
                    out,
                    "// Code generated by jtd-codegen for Swift v{}", 
                    env!("CARGO_PKG_VERSION")
                )?;
                writeln!(out)?;
                writeln!(out, "import Foundation")?;
                
                if state.needs_any_codable {
                    writeln!(out)?;
                    writeln!(out, "// AnyCodable for handling arbitrary JSON values")?;
                    writeln!(out, "public struct AnyCodable: Codable {{")?;
                    writeln!(out, "    public let value: Any")?;
                    writeln!(out, "    ")?;
                    writeln!(out, "    public init(_ value: Any) {{")?;
                    writeln!(out, "        self.value = value")?;
                    writeln!(out, "    }}")?;
                    writeln!(out, "    ")?;
                    writeln!(out, "    public init(from decoder: Decoder) throws {{")?;
                    writeln!(out, "        let container = try decoder.singleValueContainer()")?;
                    writeln!(out, "        if let intValue = try? container.decode(Int.self) {{")?;
                    writeln!(out, "            value = intValue")?;
                    writeln!(out, "        }} else if let doubleValue = try? container.decode(Double.self) {{")?;
                    writeln!(out, "            value = doubleValue")?;
                    writeln!(out, "        }} else if let stringValue = try? container.decode(String.self) {{")?;
                    writeln!(out, "            value = stringValue")?;
                    writeln!(out, "        }} else if let boolValue = try? container.decode(Bool.self) {{")?;
                    writeln!(out, "            value = boolValue")?;
                    writeln!(out, "        }} else if container.decodeNil() {{")?;
                    writeln!(out, "            value = NSNull()")?;
                    writeln!(out, "        }} else if let arrayValue = try? container.decode([AnyCodable].self) {{")?;
                    writeln!(out, "            value = arrayValue.map {{ $0.value }}")?;
                    writeln!(out, "        }} else if let dictValue = try? container.decode([String: AnyCodable].self) {{")?;
                    writeln!(out, "            value = dictValue.mapValues {{ $0.value }}")?;
                    writeln!(out, "        }} else {{")?;
                    writeln!(out, "            throw DecodingError.dataCorrupted(DecodingError.Context(codingPath: decoder.codingPath, debugDescription: \"Unable to decode value\"))")?;
                    writeln!(out, "        }}")?;
                    writeln!(out, "    }}")?;
                    writeln!(out, "    ")?;
                    writeln!(out, "    public func encode(to encoder: Encoder) throws {{")?;
                    writeln!(out, "        var container = encoder.singleValueContainer()")?;
                    writeln!(out, "        if let intValue = value as? Int {{")?;
                    writeln!(out, "            try container.encode(intValue)")?;
                    writeln!(out, "        }} else if let doubleValue = value as? Double {{")?;
                    writeln!(out, "            try container.encode(doubleValue)")?;
                    writeln!(out, "        }} else if let stringValue = value as? String {{")?;
                    writeln!(out, "            try container.encode(stringValue)")?;
                    writeln!(out, "        }} else if let boolValue = value as? Bool {{")?;
                    writeln!(out, "            try container.encode(boolValue)")?;
                    writeln!(out, "        }} else if value is NSNull {{")?;
                    writeln!(out, "            try container.encodeNil()")?;
                    writeln!(out, "        }} else if let arrayValue = value as? [Any] {{")?;
                    writeln!(out, "            try container.encode(arrayValue.map {{ AnyCodable($0) }})")?;
                    writeln!(out, "        }} else if let dictValue = value as? [String: Any] {{")?;
                    writeln!(out, "            try container.encode(dictValue.mapValues {{ AnyCodable($0) }})")?;
                    writeln!(out, "        }} else {{")?;
                    writeln!(out, "            throw EncodingError.invalidValue(value, EncodingError.Context(codingPath: encoder.codingPath, debugDescription: \"Unable to encode value\"))")?;
                    writeln!(out, "        }}")?;
                    writeln!(out, "    }}")?;
                    writeln!(out, "}}")?;
                    writeln!(out)?;
                }

                None
            }

            target::Item::Postamble => None,

            target::Item::Alias {
                metadata,
                name,
                type_,
            } => {
                writeln!(out)?;
                write!(out, "{}", description(&metadata, 0))?;
                writeln!(out, "public typealias {} = {}", name, type_)?;

                None
            }

            target::Item::Enum {
                metadata,
                name,
                members,
            } => {
                if let Some(s) = metadata.get("swiftType").and_then(|v| v.as_str()) {
                    return Ok(Some(s.into()));
                }

                writeln!(out)?;
                write!(out, "{}", description(&metadata, 0))?;
                writeln!(out, "public enum {}: String, Codable, CaseIterable {{", name)?;

                for member in members {
                    let description = enum_variant_description(&metadata, 1, &member.json_value);
                    write!(out, "{}", description)?;
                    writeln!(out, "    case {} = {:?}", member.name, member.json_value)?;
                }

                writeln!(out, "}}")?;

                None
            }

            target::Item::Struct {
                metadata,
                name,
                has_additional: _,
                fields,
            } => {
                if let Some(s) = metadata.get("swiftType").and_then(|v| v.as_str()) {
                    return Ok(Some(s.into()));
                }

                writeln!(out)?;
                write!(out, "{}", description(&metadata, 0))?;
                writeln!(out, "public struct {}: Codable {{", name)?;

                for field in &fields {
                    let description = description(&field.metadata, 1);
                    write!(out, "{}", description)?;
                    
                    if field.optional {
                        writeln!(out, "    public let {}: {}?", field.name, field.type_)?;
                    } else {
                        writeln!(out, "    public let {}: {}", field.name, field.type_)?;
                    }
                }

                if !fields.is_empty() {
                    writeln!(out)?;
                    writeln!(out, "    private enum CodingKeys: String, CodingKey {{")?;
                    for field in &fields {
                        if field.name != field.json_name {
                            writeln!(out, "        case {} = {:?}", field.name, field.json_name)?;
                        } else {
                            writeln!(out, "        case {}", field.name)?;
                        }
                    }
                    writeln!(out, "    }}")?;
                }

                writeln!(out, "}}")?;

                None
            }

            target::Item::Discriminator {
                metadata,
                name,
                variants,
                ..
            } => {
                if let Some(s) = metadata.get("swiftType").and_then(|v| v.as_str()) {
                    return Ok(Some(s.into()));
                }

                writeln!(out)?;
                write!(out, "{}", description(&metadata, 0))?;
                writeln!(out, "public enum {}: Codable {{", name)?;

                for variant in &variants {
                    writeln!(out, "    case {}({})", variant.field_name, variant.type_name)?;
                }

                writeln!(out, "}}")?;

                None
            }

            target::Item::DiscriminatorVariant {
                metadata,
                name,
                tag_json_name,
                tag_value,
                fields,
                ..
            } => {
                if let Some(s) = metadata.get("swiftType").and_then(|v| v.as_str()) {
                    return Ok(Some(s.into()));
                }

                writeln!(out)?;
                write!(out, "{}", description(&metadata, 0))?;
                writeln!(out, "public struct {}: Codable {{", name)?;

                for field in &fields {
                    let description = description(&field.metadata, 1);
                    write!(out, "{}", description)?;
                    
                    if field.optional {
                        writeln!(out, "    public let {}: {}?", field.name, field.type_)?;
                    } else {
                        writeln!(out, "    public let {}: {}", field.name, field.type_)?;
                    }
                }

                writeln!(out)?;
                writeln!(out, "    private enum CodingKeys: String, CodingKey {{")?;
                writeln!(out, "        case {} = {:?}", 
                    FIELD_NAMING_CONVENTION.inflect(&[tag_json_name.clone()]), 
                    tag_json_name)?;
                for field in &fields {
                    if field.name != field.json_name {
                        writeln!(out, "        case {} = {:?}", field.name, field.json_name)?;
                    } else {
                        writeln!(out, "        case {}", field.name)?;
                    }
                }
                writeln!(out, "    }}")?;

                writeln!(out)?;
                writeln!(out, "    public init(from decoder: Decoder) throws {{")?;
                writeln!(out, "        let container = try decoder.container(keyedBy: CodingKeys.self)")?;
                writeln!(out, "        let discriminator = try container.decode(String.self, forKey: .{})", 
                    FIELD_NAMING_CONVENTION.inflect(&[tag_json_name.clone()]))?;
                writeln!(out, "        guard discriminator == {:?} else {{", tag_value)?;
                writeln!(out, "            throw DecodingError.dataCorrupted(DecodingError.Context(")?;
                writeln!(out, "                codingPath: decoder.codingPath,")?;
                writeln!(out, "                debugDescription: \"Invalid discriminator value: \\(discriminator)\"")?;
                writeln!(out, "            ))")?;
                writeln!(out, "        }}")?;
                for field in &fields {
                    if field.optional {
                        writeln!(out, "        self.{} = try container.decodeIfPresent({}.self, forKey: .{})", 
                            field.name, field.type_, field.name)?;
                    } else {
                        writeln!(out, "        self.{} = try container.decode({}.self, forKey: .{})", 
                            field.name, field.type_, field.name)?;
                    }
                }
                writeln!(out, "    }}")?;

                writeln!(out)?;
                writeln!(out, "    public func encode(to encoder: Encoder) throws {{")?;
                writeln!(out, "        var container = encoder.container(keyedBy: CodingKeys.self)")?;
                writeln!(out, "        try container.encode({:?}, forKey: .{})", 
                    tag_value, FIELD_NAMING_CONVENTION.inflect(&[tag_json_name.clone()]))?;
                for field in &fields {
                    if field.optional {
                        writeln!(out, "        try container.encodeIfPresent(self.{}, forKey: .{})", 
                            field.name, field.name)?;
                    } else {
                        writeln!(out, "        try container.encode(self.{}, forKey: .{})", 
                            field.name, field.name)?;
                    }
                }
                writeln!(out, "    }}")?;

                writeln!(out, "}}")?;

                None
            }
        })
    }
}

#[derive(Default)]
pub struct FileState {
    needs_any_codable: bool,
}

fn description(metadata: &BTreeMap<String, Value>, indent: usize) -> String {
    doc(indent, jtd_codegen::target::metadata::description(metadata))
}

fn enum_variant_description(
    metadata: &BTreeMap<String, Value>,
    indent: usize,
    value: &str,
) -> String {
    doc(
        indent,
        jtd_codegen::target::metadata::enum_variant_description(metadata, value),
    )
}

fn doc(indent: usize, s: &str) -> String {
    let prefix = "    ".repeat(indent);
    jtd_codegen::target::fmt::comment_block(
        &format!("{}/**", prefix),
        &format!("{} * ", prefix),
        &format!("{} */", prefix),
        s,
    )
}

#[cfg(test)]
mod tests {
    mod std_tests {
        jtd_codegen_test::std_test_cases!(&crate::Target::new());
    }

    mod optional_std_tests {
        jtd_codegen_test::strict_std_test_case!(
            &crate::Target::new(),
            empty_and_nonascii_properties
        );

        jtd_codegen_test::strict_std_test_case!(
            &crate::Target::new(),
            empty_and_nonascii_enum_values
        );
    }
}