// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

/**
 * A description for discriminator
 */
public enum RootDiscriminatorWithDescription: Codable {
    case bar(RootDiscriminatorWithDescriptionBar)
}

/**
 * A description for discriminator variant
 */
public struct RootDiscriminatorWithDescriptionBar: Codable {

    private enum CodingKeys: String, CodingKey {
        case foo = "foo"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .foo)
        guard discriminator == "bar" else {
            throw DecodingError.dataCorrupted(DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Invalid discriminator value: \(discriminator)"
            ))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode("bar", forKey: .foo)
    }
}

/**
 * A description for enum
 */
public enum RootEnumWithDescription: String, Codable, CaseIterable {
    /**
     * A description for X
     */
    case x = "X"
    /**
     * A description for Y
     */
    case y = "Y"
    /**
     * A description for Z
     */
    case z = "Z"
}

/**
 * A description for properties
 */
public struct RootPropertiesWithDescription: Codable {
}

public struct Root: Codable {
    /**
     * A description for discriminator
     */
    public let discriminatorWithDescription: RootDiscriminatorWithDescription
    /**
     * A description for enum
     */
    public let enumWithDescription: RootEnumWithDescription
    /**
     * Whereas disregard and contempt for human rights have resulted in
     * barbarous acts which have outraged the conscience of mankind, and the
     * advent of a world in which human beings shall enjoy freedom of speech and
     * belief and freedom from fear and want has been proclaimed as the highest
     * aspiration of the common people,
     */
    public let longDescription: String
    /**
     * A description for properties
     */
    public let propertiesWithDescription: RootPropertiesWithDescription
    /**
     * A description for ref
     */
    public let refWithDescription: Baz
    /**
     * A description for string
     */
    public let stringWithDescription: String

    private enum CodingKeys: String, CodingKey {
        case discriminatorWithDescription = "discriminator_with_description"
        case enumWithDescription = "enum_with_description"
        case longDescription = "long_description"
        case propertiesWithDescription = "properties_with_description"
        case refWithDescription = "ref_with_description"
        case stringWithDescription = "string_with_description"
    }
}

/**
 * A description for a definition
 */
public typealias Baz = String
