// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public enum RootFooBar: String, Codable, CaseIterable {
    case x = "x"
    case y = "y"
}

public struct RootFoo: Codable {
    public let bar: RootFooBar

    private enum CodingKeys: String, CodingKey {
        case bar
    }
}

public enum RootFooBar0: String, Codable, CaseIterable {
    case x0 = "x"
    case y0 = "y"
}

public struct Root: Codable {
    public let foo: RootFoo
    public let fooBar: RootFooBar0

    private enum CodingKeys: String, CodingKey {
        case foo
        case fooBar = "foo_bar"
    }
}
