// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root0: Codable {
    public let bar: String
    public let baz: [Bool]
    public let foo: Bool
    public let quux: [Bool]

    private enum CodingKeys: String, CodingKey {
        case bar
        case baz
        case foo
        case quux
    }
}

public typealias Root = Root0?
