// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public let foo: Date?

    private enum CodingKeys: String, CodingKey {
        case foo
    }
}
