// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public let bar: [String]?
    public let baz: Bool?
    public let foo: String?

    private enum CodingKeys: String, CodingKey {
        case bar
        case baz
        case foo
    }
}
