// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public typealias Root = Foo0

public typealias Bar = Bar0

public typealias Foo = Bar

public typealias Bar0 = String

public typealias Foo0 = Foo
