// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct RootFooBar: Codable {
    public let x: Bool

    private enum CodingKeys: String, CodingKey {
        case x
    }
}

public struct RootFoo: Codable {
    public let bar: RootFooBar

    private enum CodingKeys: String, CodingKey {
        case bar
    }
}

public struct RootFooBar0: Codable {
    public let x: String

    private enum CodingKeys: String, CodingKey {
        case x
    }
}

public struct Root: Codable {
    public let foo: RootFoo
    public let fooBar: RootFooBar0

    private enum CodingKeys: String, CodingKey {
        case foo
        case fooBar = "foo_bar"
    }
}
