// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public let notnullRefNotnullString: NotnullRefNotnullString
    public let notnullRefNullString: NotnullRefNullString
    public let notnullString: NotnullString
    public let nullRefNotnullString: NullRefNotnullString
    public let nullRefNullString: NullRefNullString
    public let nullString: NullString

    private enum CodingKeys: String, CodingKey {
        case notnullRefNotnullString = "notnull_ref_notnull_string"
        case notnullRefNullString = "notnull_ref_null_string"
        case notnullString = "notnull_string"
        case nullRefNotnullString = "null_ref_notnull_string"
        case nullRefNullString = "null_ref_null_string"
        case nullString = "null_string"
    }
}

public typealias NotnullRefNotnullString = NotnullString

public typealias NotnullRefNullString = NullString

public typealias NotnullString = String

public typealias NullRefNotnullString = NotnullString?

public typealias NullRefNullString = NullString?

public typealias NullString = String?
