// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public let for_: For
    public let object: Object

    private enum CodingKeys: String, CodingKey {
        case for_ = "for"
        case object
    }
}

public typealias For = String

public typealias Object = String
