// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public enum Root: Codable {
    case bar(RootBar)
}

public struct RootBar: Codable {
    public let baz: [String]?
    public let quux: Bool?

    private enum CodingKeys: String, CodingKey {
        case foo = "foo"
        case baz
        case quux
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .foo)
        guard discriminator == "bar" else {
            throw DecodingError.dataCorrupted(DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Invalid discriminator value: \(discriminator)"
            ))
        }
        self.baz = try container.decodeIfPresent([String].self, forKey: .baz)
        self.quux = try container.decodeIfPresent(Bool.self, forKey: .quux)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode("bar", forKey: .foo)
        try container.encodeIfPresent(self.baz, forKey: .baz)
        try container.encodeIfPresent(self.quux, forKey: .quux)
    }
}
