// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public enum Root: String, Codable, CaseIterable {
    case defaultName = ""
    case foo = "$foo"
    case foo0 = "0foo"
    case foo1 = "_foo"
    case fooBar = "foo\nbar"
    case fooBar0 = "foo bar"
    case foo0bar = "foo0bar"
    case fooBar1 = "foo﷽bar"
}
