// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public enum Root: Codable {
    case barBaz(RootBarBaz)
    case quux(RootQuux)
}

public struct RootBarBaz: Codable {
    public let baz: String

    private enum CodingKeys: String, CodingKey {
        case foo = "foo"
        case baz
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .foo)
        guard discriminator == "BAR_BAZ" else {
            throw DecodingError.dataCorrupted(DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Invalid discriminator value: \(discriminator)"
            ))
        }
        self.baz = try container.decode(String.self, forKey: .baz)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode("BAR_BAZ", forKey: .foo)
        try container.encode(self.baz, forKey: .baz)
    }
}

public struct RootQuux: Codable {
    public let quuz: String

    private enum CodingKeys: String, CodingKey {
        case foo = "foo"
        case quuz
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .foo)
        guard discriminator == "QUUX" else {
            throw DecodingError.dataCorrupted(DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Invalid discriminator value: \(discriminator)"
            ))
        }
        self.quuz = try container.decode(String.self, forKey: .quuz)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode("QUUX", forKey: .foo)
        try container.encode(self.quuz, forKey: .quuz)
    }
}
