// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct Root: Codable {
    public let defaultName: String
    public let foo: String
    public let foo0: String
    public let foo1: String
    public let fooBar: String
    public let fooBar0: String
    public let foo0bar: String
    public let fooBar1: String

    private enum CodingKeys: String, CodingKey {
        case defaultName = ""
        case foo = "$foo"
        case foo0 = "0foo"
        case foo1 = "_foo"
        case fooBar = "foo\nbar"
        case fooBar0 = "foo bar"
        case foo0bar
        case fooBar1 = "foo﷽bar"
    }
}
