// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public enum RootOverrideTypeDiscriminator: Codable {
    case bar(RootOverrideTypeDiscriminatorBar)
    case baz(RootOverrideTypeDiscriminatorBaz)
}

public struct RootOverrideTypeDiscriminatorBar: Codable {

    private enum CodingKeys: String, CodingKey {
        case foo = "foo"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .foo)
        guard discriminator == "bar" else {
            throw DecodingError.dataCorrupted(DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Invalid discriminator value: \(discriminator)"
            ))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode("bar", forKey: .foo)
    }
}

public struct RootOverrideTypeDiscriminatorBaz: Codable {

    private enum CodingKeys: String, CodingKey {
        case foo = "foo"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let discriminator = try container.decode(String.self, forKey: .foo)
        guard discriminator == "baz" else {
            throw DecodingError.dataCorrupted(DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Invalid discriminator value: \(discriminator)"
            ))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode("baz", forKey: .foo)
    }
}

public enum RootOverrideTypeEnum: String, Codable, CaseIterable {
    case bar = "BAR"
    case foo = "FOO"
}

public struct RootOverrideTypeProperties: Codable {
}

public struct Root: Codable {
    public let overrideElementsContainer: [String]
    public let overrideTypeDiscriminator: RootOverrideTypeDiscriminator
    public let overrideTypeEnum: RootOverrideTypeEnum
    public let overrideTypeExpr: String
    public let overrideTypeProperties: RootOverrideTypeProperties
    public let overrideValuesContainer: [String: String]

    private enum CodingKeys: String, CodingKey {
        case overrideElementsContainer = "override_elements_container"
        case overrideTypeDiscriminator = "override_type_discriminator"
        case overrideTypeEnum = "override_type_enum"
        case overrideTypeExpr = "override_type_expr"
        case overrideTypeProperties = "override_type_properties"
        case overrideValuesContainer = "override_values_container"
    }
}
