// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public typealias Root = String

public typealias DefaultName = String

public typealias Foo = String

public typealias Foo0 = String

public typealias Foo1 = String

public typealias FooBar = String

public typealias FooBar0 = String

public typealias Foo0bar = String

public typealias FooBar1 = String
