// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public enum Root0: String, Codable, CaseIterable {
    case bar = "Bar"
    case baz = "Baz"
    case foo = "Foo"
}

public typealias Root = Root0?
