// Code generated by jtd-codegen for Swift v0.2.1

import Foundation

public struct RootNestedIdInitialism: Codable {
    public let json: String
    public let normalword: String

    private enum CodingKeys: String, CodingKey {
        case json
        case normalword
    }
}

public struct Root: Codable {
    public let http: String
    public let id: String
    public let nestedIdInitialism: RootNestedIdInitialism
    public let utf8: String
    public let wordWithEmbeddedIdInitialism: String
    public let wordWithTrailingInitialismId: String

    private enum CodingKeys: String, CodingKey {
        case http
        case id
        case nestedIdInitialism = "nested_id_initialism"
        case utf8
        case wordWithEmbeddedIdInitialism = "word_with_embedded_id_initialism"
        case wordWithTrailingInitialismId = "word_with_trailing_initialism_id"
    }
}
